### ISSUE TITLE
Conflict register with Servo library when using Timer Interrupt 1

### ISSUE THREAD

**Issue by Huyyuh2000** [khoih-prog/TimerInterrupt#20]
### Describe the bug

When I was using Timer 1 to read value form current sensor using Timer1 for servo control project. It occurred an error like  image below. I haven't check it clearly but I think it is conflict with servo library form Arduino Ide 

### Screenshots

![image](https://user-images.githubusercontent.com/53828364/121913792-e6090180-cd5b-11eb-94b2-98b4eec30187.png)
### Information

  

```
Arduino IDE version: 1.8.13
Arduino Nano
Servo.h

**Comment by khoih-prog** [comment]
Without the [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example), no one will spend time to understand what's wrong with your code.

On the other hand, using TimerInterrupt and ISR requires more sophisticated knowledge about hardware, coding in order to **prevent conflicts**. So you have to check, research and understand why there is conflict and **use different Time**r to avoid the issue.

I'm closing the issue now, and only reopen when you post MRE and prove this is a bug of the [TimerInterrupt library](https://github.com/khoih-prog/TimerInterrupt).

Also you have to post the code correctly, by using code tag ( <> or tripple ticks), not just a useless picture.
